// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	users "be9/mnroom/features/users"

	mock "github.com/stretchr/testify/mock"
)

// UserData is an autogenerated mock type for the Data type
type UserData struct {
	mock.Mock
}

// DeleteData provides a mock function with given fields: id
func (_m *UserData) DeleteData(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllData provides a mock function with given fields:
func (_m *UserData) GetAllData() ([]users.Core, error) {
	ret := _m.Called()

	var r0 []users.Core
	if rf, ok := ret.Get(0).(func() []users.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetData provides a mock function with given fields: id
func (_m *UserData) GetData(id int) (users.Core, error) {
	ret := _m.Called(id)

	var r0 users.Core
	if rf, ok := ret.Get(0).(func(int) users.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(users.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertData provides a mock function with given fields: insert
func (_m *UserData) InsertData(insert users.Core) (int, error) {
	ret := _m.Called(insert)

	var r0 int
	if rf, ok := ret.Get(0).(func(users.Core) int); ok {
		r0 = rf(insert)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.Core) error); ok {
		r1 = rf(insert)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateData provides a mock function with given fields: id, insert
func (_m *UserData) UpdateData(id int, insert users.Core) (int, error) {
	ret := _m.Called(id, insert)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, users.Core) int); ok {
		r0 = rf(id, insert)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, users.Core) error); ok {
		r1 = rf(id, insert)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserData interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserData creates a new instance of UserData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserData(t mockConstructorTestingTNewUserData) *UserData {
	mock := &UserData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
